version: '3.7'
services:
  rt:
    container_name: mongo
    build:
      context: .
      args:
        CI: mongo:$RT-bionic
    image: $REG/rt/$SRV:$RT
    # ports:
    #   - '27017:27017'
    volumes:
      - /srv/db/mongo/db:/data/db
      - /srv/db/mongo/configdb:/data/configdb
    restart: always

networks:
  default:
    external:
      name: meta_db